name: ci
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  pre-commit:
    name: 'pre-commit'
    runs-on: ubuntu-latest
    environment: sandbox

    defaults:
      run:
        shell: bash

    steps:
      - name: pre-commit
        uses:  'aleksandar-babic/gh-composite-actions/pre-commit@main'
